# Generated by Django 4.1 on 2022-10-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_likedetails_postcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedetails',
            name='like',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
