# Generated by Django 4.1 on 2022-10-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_comments_postcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
