# Generated by Django 4.1 on 2022-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_is_liked_remove_post_likes_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
