# Generated by Django 4.1 on 2022-10-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_postlike_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
