# Generated by Django 4.1 on 2022-10-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_postlike_is_liked_remove_postlike_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_follower', models.CharField(max_length=100)),
                ('user_following', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
