# Generated by Django 4.1 on 2022-10-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_followprofile_profile_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_ac',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
