# Generated by Django 4.1 on 2022-10-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_following_ac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followprofile',
            old_name='user_follower',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='followprofile',
            old_name='user_following',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_ac',
        ),
    ]
